trigger:
- main

variables:
  imageRepository: 'simpleapi'
  tag: '$(Build.BuildId)'
  acrName:'myecommer'
  acrLoginServer:'myecommer.azurecr.io'


stages:


- stage: Build
  displayName: Build and Push Image

  jobs:

  - job: DockerBuild

    pool:
      vmImage: ubuntu-latest

    steps:

    - checkout: self

    # Verify Dockerfile exists
    - bash: |
        echo "Current directory:"
        pwd
        echo "Files:"
        find $(Build.SourcesDirectory) -maxdepth 2 -type f
      displayName: Verify files
      
    - task: AzureCLI@2
      displayName: Login to Azure and ACR
      inputs:
        azureSubscription: 'mynew-Connection'
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az acr login --name $(acrName)

    - bash: |
        docker build \
          -t $(acrLoginServer)/$(imageRepository):$(tag) \
          -t $(acrLoginServer)/$(imageRepository):latest \
          $(Build.SourcesDirectory)

        docker push $(acrLoginServer)/$(imageRepository):$(tag)
        docker push $(acrLoginServer)/$(imageRepository):latest
      displayName: Build and Push Docker Image
    